.TH "ANSICInformation/ANSIC_CODE.h" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANSICInformation/ANSIC_CODE.h \- 
.PP
このファイルは、ANSICのソースコードを省略させるためのマクロ文が含まれている  

.SH SYNOPSIS
.br
.PP
\fC#include 'AST.h'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_1\fP (\fBAST\fP *target)"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_2\fP (\fBAST\fP *target)"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_3\fP (\fBAST\fP *target)"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_4\fP (\fBAST\fP *target)"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_5\fP (\fBAST\fP *target)"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_6\fP (\fBAST\fP *target)"
.br
.ti -1c
.RI "\fBAST\fP * \fBASTLIST_ITERATOR_7\fP (\fBAST\fP *target)"
.br
.in -1c
.SH "説明"
.PP 
このファイルは、ANSICのソースコードを省略させるためのマクロ文が含まれている 

\fB作者:\fP
.RS 4
faithnh 
.RE
.PP

.SH "関数"
.PP 
.SS "\fBAST\fP* ASTLIST_ITERATOR_1 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの１番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの１番目の子ノードが返される。 
.RE
.PP

.SS "\fBAST\fP* ASTLIST_ITERATOR_2 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの２番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの２番目の子ノードが返される。 
.RE
.PP

.SS "\fBAST\fP* ASTLIST_ITERATOR_3 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの３番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの３番目の子ノードが返される。 
.RE
.PP

.SS "\fBAST\fP* ASTLIST_ITERATOR_4 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの４番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの４番目の子ノードが返される。 
.RE
.PP

.SS "\fBAST\fP* ASTLIST_ITERATOR_5 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの５番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの５番目の子ノードが返される。 
.RE
.PP

.SS "\fBAST\fP* ASTLIST_ITERATOR_6 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの６番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの６番目の子ノードが返される。 
.RE
.PP

.SS "\fBAST\fP* ASTLIST_ITERATOR_7 (\fBAST\fP *target)\fC [inline]\fP"対象のASTノードの７番目の子ノードの取得する。
.PP
\fB引数:\fP
.RS 4
\fItarget\fP 対象のASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
対象のASTノードの７番目の子ノードが返される。 
.RE
.PP

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
