.TH "dd_information" 3 "6 Jan 2011" "Version 1.0" "ANSIC<Ø Äüë" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dd_information \- 
.SH SYNOPSIS
.br
.PP
.SS "å¤‰æ•°"

.in +1c
.ti -1c
.RI "CSTLString * \fBdd_variable_name\fP"
.br
.ti -1c
.RI "\fBEXPR_SLICING\fP * \fBdd_target\fP"
.br
.in -1c

.SH "ä½œè€…"
.PP 
ANSIC<Ø Äüë¤Î¥½¡¼¥¹¤«¤é Doxygen ¤Ë¤è¤êÀ¸À®¤·¤Þ¤·¤¿¡£
