.TH "divition_information" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
divition_information \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DivitionInformation.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.RI "\fI対象の式 \fP"
.ti -1c
.RI "CSTLString * \fBstatement\fP"
.br
.RI "\fI除算か剰余かどうかのタイプ　０：除算式　１：剰余式 \fP"
.ti -1c
.RI "ARRAY_OFFSET_LIST * \fBidentifiers\fP"
.br
.RI "\fI除算および剰余以下の式 \fP"
.in -1c
.SH "説明"
.PP 
除算および剰余算に関する情報を格納する。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
