.TH "ANSICInformation/FreeMemInfo.h" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANSICInformation/FreeMemInfo.h \- 
.PP
このファイルは、メモリ解放関係の関数から、メモリ解放関係の情報を取得する命令が含まれている。 具体的には、C言語プログラム上にあるfree関数から、どの変数が解放されているかどうかについて取得する。  

.SH SYNOPSIS
.br
.PP
\fC#include 'PointerArrayControl.h'\fP
.br
\fC#include 'FunctionInformation.h'\fP
.br

.SS "データ構造"

.in +1c
.ti -1c
.RI "struct \fBfreemem_info\fP"
.br
.in -1c
.SS "型定義"

.in +1c
.ti -1c
.RI "typedef struct \fBfreemem_info\fP \fBFREEMEMINFO\fP"
.br
.in -1c
.SS "関数"

.in +1c
.ti -1c
.RI "\fBFREEMEMINFO\fP * \fBnew_FREEMEMINFO\fP (ARRAY_OFFSET_LIST *free_variable)"
.br
.ti -1c
.RI "void \fBgetFreememInfo\fP (\fBFREEMEMINFO\fP **freememinfo, \fBAST\fP *call_function, FUNCTION_INFORMATION_LIST *function_information_list, VARIABLE_TABLE_LIST *vtlist, \fBAST\fP *target_statement)"
.br
.ti -1c
.RI "void \fBprintFREEMEMINFO\fP (\fBFREEMEMINFO\fP *freememinfo)"
.br
.in -1c
.SH "説明"
.PP 
このファイルは、メモリ解放関係の関数から、メモリ解放関係の情報を取得する命令が含まれている。 具体的には、C言語プログラム上にあるfree関数から、どの変数が解放されているかどうかについて取得する。 

\fB作者:\fP
.RS 4
faithnh 
.RE
.PP

.SH "型定義"
.PP 
.SS "typedef struct \fBfreemem_info\fP  \fBFREEMEMINFO\fP"メモリ確保関係に関係する変数が含まれる。これは、メモリ解放関数の挙動に合わせて検証式を追加するために用いる。 
.SH "関数"
.PP 
.SS "void getFreememInfo (\fBFREEMEMINFO\fP **freememinfo, \fBAST\fP *call_function, FUNCTION_INFORMATION_LIST *function_information_list, VARIABLE_TABLE_LIST *vtlist, \fBAST\fP *target_statement)"対象の関数へのASTノードからfree関数を見つけ、それに関する情報を取得する。
.PP
\fB引数:\fP
.RS 4
\fIfreememinfo\fP 取得先のメモリ解放関係の情報 
.br
\fIcall_function\fP 対象の関数へのASTノード 
.br
\fIfunction_information_list\fP 関数に関する情報のリスト 
.br
\fIvtlist\fP 変数テーブルの情報 
.br
\fItarget_statement\fP 対象の関数が位置している式へのASTノード
.RE
.PP
\fB戻り値:\fP
.RS 4
なし 
.RE
.PP

.SS "\fBFREEMEMINFO\fP* new_FREEMEMINFO (ARRAY_OFFSET_LIST *free_variable)"新しいメモリ解放関係の情報を生成する。
.PP
\fB引数:\fP
.RS 4
\fIfree_variable\fP 新しい解放先の変数に関するオフセットリスト
.RE
.PP
\fB戻り値:\fP
.RS 4
新しく生成されたメモリ解放関係の情報へのアドレスを返す。 
.RE
.PP

.SS "void printFREEMEMINFO (\fBFREEMEMINFO\fP *freememinfo)"指定したメモリ解放関係の情報を出力する。
.PP
\fB引数:\fP
.RS 4
\fIfreememinfo\fP 出力するメモリ解放関係の情報
.RE
.PP
\fB戻り値:\fP
.RS 4
なし 
.RE
.PP

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
