.TH "freemem_info" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
freemem_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FreeMemInfo.h>\fP
.SH "説明"
.PP 
メモリ確保関係に関係する変数が含まれる。これは、メモリ解放関数の挙動に合わせて検証式を追加するために用いる。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
