.TH "include_data" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PreProcess.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "int \fBline\fP"
.br
.RI "\fIincludeファイルの名前 \fP"
.in -1c
.SH "説明"
.PP 
インクルードファイルに関する情報が格納される。これは、検証式付加時にインクルードファイルを付加するのに使用する。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
