.TH "ANSICInformation/MallocNumber.h" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANSICInformation/MallocNumber.h \- 
.PP
これはどのmalloc用識別番号を付加する関数を生成するための命令が含まれている。  

.SH SYNOPSIS
.br
.PP
\fC#include '../Library/CSTLString.h'\fP
.br
\fC#include 'PreProcess.h'\fP
.br

.SS "関数"

.in +1c
.ti -1c
.RI "void \fBgenerateMallocNumber\fP (CSTLString *target_directory)"
.br
.ti -1c
.RI "void \fBinsertMallocNumberHeadder\fP (INCLUDE_LIST *include_list)"
.br
.in -1c
.SH "説明"
.PP 
これはどのmalloc用識別番号を付加する関数を生成するための命令が含まれている。 

\fB作者:\fP
.RS 4
faithnh 
.RE
.PP

.SH "関数"
.PP 
.SS "void generateMallocNumber (CSTLString *target_directory)"malloc用識別番号付加関数をカレントディレクトリ上に生成させる。 
.PP
\fB引数:\fP
.RS 4
\fItarget_directory\fP 作成するディレクトリ先
.RE
.PP
\fB戻り値:\fP
.RS 4
なし
.RE
.PP
malloc用識別番号関数をカレントディレクトリ上に生成させる。 
.PP
\fB引数:\fP
.RS 4
\fItarget_directory\fP 作成するディレクトリ先
.RE
.PP
\fB戻り値:\fP
.RS 4
なし 
.RE
.PP

.SS "void insertMallocNumberHeadder (INCLUDE_LIST *include_list)"インクルード情報にmalloc用識別番号付加関数が含まれているヘッダーファイルを追加させる。。 
.PP
\fB引数:\fP
.RS 4
\fIinclude_list\fP インクルード情報へのリスト
.RE
.PP
\fB戻り値:\fP
.RS 4
なし
.RE
.PP
インクルード情報にmalloc用識別番号付加関数が含まれているヘッダーファイルを追加させる。 
.PP
\fB引数:\fP
.RS 4
\fIinclude_list\fP インクルード情報へのリスト
.RE
.PP
\fB戻り値:\fP
.RS 4
なし 
.RE
.PP

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
