.TH "memory_allocation_info" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memory_allocation_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MemallocInfo.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "ARRAY_OFFSET_LIST * \fBrealloc_target\fP"
.br
.RI "\fIsizeofの型名 \fP"
.ti -1c
.RI "CSTLString * \fBsize\fP"
.br
.RI "\fIrealloc時のターゲット変数の配列オフセットリスト \fP"
.in -1c
.SH "説明"
.PP 
メモリ割り当てに関する情報を格納するための構造体。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
