.TH "param_information" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
param_information \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FunctionInformation.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "CSTLString * \fBparam_name\fP"
.br
.RI "\fIパラメータの型 \fP"
.ti -1c
.RI "int \fBarray_level\fP"
.br
.RI "\fIパラメータの名前 \fP"
.ti -1c
.RI "int \fBpointer_level\fP"
.br
.RI "\fI配列のレベル \fP"
.ti -1c
.RI "int \fBin_out_flag\fP"
.br
.RI "\fIポインタのレベル \fP"
.in -1c
.SH "説明"
.PP 
引数に関する情報 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
