.TH "return_info" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
return_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Return_Info.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "ARRAY_OFFSET_LIST * \fBreturn_array_offset_list\fP"
.br
.RI "\fIリターン命令自体へのノードへのアドレス \fP"
.in -1c
.SH "説明"
.PP 
リターン命令に関する情報が含まれている。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
