.TH "struct_table" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_table \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Synbol.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "CSTLString * \fBtype\fP"
.br
.RI "\fI行数 \fP"
.ti -1c
.RI "CSTLString * \fBstruct_name\fP"
.br
.RI "\fI構造体のタイプ union:共同体 struct:構造体 \fP"
.ti -1c
.RI "VARIABLE_TABLE_LIST * \fBmember_list\fP"
.br
.RI "\fI構造体の名前 \fP"
.in -1c
.SH "説明"
.PP 
構造体に関する情報であり、プログラム中の構造体の識別するのに用いられる。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
