.TH "typedef_table" 3 "Tue Feb 1 2011" "Version 1.0" "ValidateStatementAdder" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typedef_table \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Synbol.h>\fP
.SS "変数"

.in +1c
.ti -1c
.RI "CSTLString * \fBchange_type\fP"
.br
.RI "\fI対象の型定義 \fP"
.in -1c
.SH "説明"
.PP 
型定義に関する情報で、BISONによる構文解析時の型定義の認識に用いられる。 

.SH "作者"
.PP 
ValidateStatementAdderのソースから Doxygen により生成しました。
