.TH "yy_trans_info" 3 "6 Jan 2011" "Version 1.0" "ANSIC<Ø Äüë" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yy_trans_info \- 
.SH SYNOPSIS
.br
.PP
.SS "å¤‰æ•°"

.in +1c
.ti -1c
.RI "flex_int32_t \fByy_verify\fP"
.br
.ti -1c
.RI "flex_int32_t \fByy_nxt\fP"
.br
.in -1c

.SH "ä½œè€…"
.PP 
ANSIC<Ø Äüë¤Î¥½¡¼¥¹¤«¤é Doxygen ¤Ë¤è¤êÀ¸À®¤·¤Þ¤·¤¿¡£
