.TH "yyalloc" 3 "6 Jan 2011" "Version 1.0" "ANSIC<Ø Äüë" \" -*- nroff -*-
.ad l
.nh
.SH NAME
yyalloc \- 
.SH SYNOPSIS
.br
.PP
.SS "å¤‰æ•°"

.in +1c
.ti -1c
.RI "yytype_int16 \fByyss_alloc\fP"
.br
.ti -1c
.RI "\fBYYSTYPE\fP \fByyvs_alloc\fP"
.br
.in -1c

.SH "ä½œè€…"
.PP 
ANSIC<Ø Äüë¤Î¥½¡¼¥¹¤«¤é Doxygen ¤Ë¤è¤êÀ¸À®¤·¤Þ¤·¤¿¡£
